- job_name: neuralbudget-evaluator
  metrics_path: /metrics
  kubernetes_sd_configs:
    - role: endpoints
  relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_app]
      action: keep
      regex: neuralbudget-evaluator
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      action: keep
      regex: http
