apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: neuralbudget-evaluator
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: neuralbudget-evaluator
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
