apiVersion: v1
kind: Service
metadata:
  name: neuralbudget-evaluator
  labels:
    app: neuralbudget-evaluator
spec:
  type: ClusterIP
  selector:
    app: neuralbudget-evaluator
  ports:
    - name: http
      port: 80
      targetPort: http
